package com.barley.config.service.searchvo;

import com.barley.config.vo.CodeTableCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.config.service.searchvo.CodeTableSearchVO create date 2020-12-31 13:35:23
 */
public class CodeTableSearchVO extends CodeTableCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String tableName;

    @Getter
    @Setter
    private String codeName;

    @Getter
    @Setter
    private String codeValue;

    @Getter
    @Setter
    private Long insertBy;

    @Getter
    @Setter
    private Long updateBy;

    @Getter
    @Setter
    private java.time.LocalDateTime insertTime;

    @Getter
    @Setter
    private java.time.LocalDateTime updateTime;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(tableName)) {
            criteria.andTableNameEqualTo(tableName);
        }
        
        if(StringUtils.isNotEmpty(codeName)) {
            criteria.andCodeNameEqualTo(codeName);
        }
        
        if(StringUtils.isNotEmpty(codeValue)) {
            criteria.andCodeValueEqualTo(codeValue);
        }
        
        if(insertBy != null) {
            criteria.andInsertByEqualTo(insertBy);
        }
        
        if(updateBy != null) {
            criteria.andUpdateByEqualTo(updateBy);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code_table
     *
     * @mbg.generated
     */
    public CodeTableSearchVO() {
        super();
    }
}