package com.barley.config.service.searchvo;

import com.barley.config.vo.FeildTypeCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.config.service.searchvo.FeildTypeSearchVO create date 2020-12-31 13:35:23
 */
public class FeildTypeSearchVO extends FeildTypeCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String typeName;

    @Getter
    @Setter
    private String component;

    @Getter
    @Setter
    private Long insertBy;

    @Getter
    @Setter
    private Long updateBy;

    @Getter
    @Setter
    private java.time.LocalDateTime insertTime;

    @Getter
    @Setter
    private java.time.LocalDateTime updateTime;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(typeName)) {
            criteria.andTypeNameEqualTo(typeName);
        }
        
        if(StringUtils.isNotEmpty(component)) {
            criteria.andComponentEqualTo(component);
        }
        
        if(insertBy != null) {
            criteria.andInsertByEqualTo(insertBy);
        }
        
        if(updateBy != null) {
            criteria.andUpdateByEqualTo(updateBy);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feild_type
     *
     * @mbg.generated
     */
    public FeildTypeSearchVO() {
        super();
    }
}