package com.barley.config.service.searchvo;

import com.barley.config.vo.FormCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.config.service.searchvo.FormSearchVO create date 2020-12-31 13:35:23
 */
public class FormSearchVO extends FormCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String formName;

    @Getter
    @Setter
    private Long insertBy;

    @Getter
    @Setter
    private Long updateBy;

    @Getter
    @Setter
    private java.time.LocalDateTime insertTime;

    @Getter
    @Setter
    private java.time.LocalDateTime updateTime;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(formName)) {
            criteria.andFormNameEqualTo(formName);
        }
        
        if(insertBy != null) {
            criteria.andInsertByEqualTo(insertBy);
        }
        
        if(updateBy != null) {
            criteria.andUpdateByEqualTo(updateBy);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated
     */
    public FormSearchVO() {
        super();
    }
}