package com.barley.system.modal;

import java.io.Serializable;
import org.barley.bo.AutomaticEntityImpl;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_biz_modular
 */
public class BizModular extends AutomaticEntityImpl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_biz_modular.list_id
     *
     * @mbg.generated
     */
    private Integer listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_biz_modular.modular
     *
     * @mbg.generated
     */
    private String modular;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_biz_modular.parent_mod_id
     *
     * @mbg.generated
     */
    private Integer parentModId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_biz_modular.describe
     *
     * @mbg.generated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_modular
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_biz_modular.list_id
     *
     * @return the value of t_biz_modular.list_id
     *
     * @mbg.generated
     */
    public Integer getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_biz_modular.list_id
     *
     * @param listId the value for t_biz_modular.list_id
     *
     * @mbg.generated
     */
    public void setListId(Integer listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_biz_modular.modular
     *
     * @return the value of t_biz_modular.modular
     *
     * @mbg.generated
     */
    public String getModular() {
        return modular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_biz_modular.modular
     *
     * @param modular the value for t_biz_modular.modular
     *
     * @mbg.generated
     */
    public void setModular(String modular) {
        this.modular = modular == null ? null : modular.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_biz_modular.parent_mod_id
     *
     * @return the value of t_biz_modular.parent_mod_id
     *
     * @mbg.generated
     */
    public Integer getParentModId() {
        return parentModId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_biz_modular.parent_mod_id
     *
     * @param parentModId the value for t_biz_modular.parent_mod_id
     *
     * @mbg.generated
     */
    public void setParentModId(Integer parentModId) {
        this.parentModId = parentModId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_biz_modular.describe
     *
     * @return the value of t_biz_modular.describe
     *
     * @mbg.generated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_biz_modular.describe
     *
     * @param describe the value for t_biz_modular.describe
     *
     * @mbg.generated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }
}