package com.barley.party.service;

import com.barley.party.mappers.DepartmentMapper;
import com.barley.party.modal.Department;
import com.barley.party.service.searchvo.DepartmentSearchVO;
import com.github.pagehelper.PageInfo;
import javax.transaction.NotSupportedException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.DepartmentBaseService create date 2020-12-25 13:03:26
 */
@Service
@Transactional
public class DepartmentServiceImpl implements DepartmentService {
    @Autowired
    protected DepartmentMapper entityMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public Department create(Department record) {
        entityMapper.insert(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public void delete(Long keyId) {
        entityMapper.deleteByPrimaryKey(keyId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public Department update(Department record) {
        entityMapper.updateByPrimaryKey(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public java.util.List<Department> findAll() {
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public Department findByPrimaryKey(Long keyId) {
        Department entity = entityMapper.selectByPrimaryKey(keyId);
        return entity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public PageInfo<Department> searchByVO(DepartmentSearchVO searchVO) {
        //TODO
        throw new RuntimeException(new NotSupportedException("no support"));
    }
}