package com.barley.party.service;

import com.barley.party.mappers.DepartmentMapper;
import com.barley.party.modal.Department;
import com.barley.party.service.searchvo.DepartmentSearchVO;
import com.github.pagehelper.Page;
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;
import java.util.List;
import org.barley.mybatis.CriteriaBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.DepartmentBaseService create date 2020-12-27 12:09:54
 */
@Service
@Transactional
public class DepartmentServiceImpl implements DepartmentService {
    @Autowired
    protected DepartmentMapper entityMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public Department create(Department record) {
        entityMapper.insert(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public void delete(Long keyId) {
        entityMapper.deleteByPrimaryKey(keyId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public Department update(Department record) {
        entityMapper.updateByPrimaryKey(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public List<Department> findAll() {
        DepartmentSearchVO searchvo = new DepartmentSearchVO();
        return entityMapper.searchByCriteria(searchvo);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public Department findByPrimaryKey(Long keyId) {
        Department entity = entityMapper.selectByPrimaryKey(keyId);
        return entity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public List<Department> searchByVO(DepartmentSearchVO searchVO) {
        PageInfo<Department> pageInfo = internalfindBySearchVO(searchVO, null, null);
        return pageInfo.getList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public PageInfo<Department> searchByVO(DepartmentSearchVO searchVO, int page, int pageSize) {
        return internalfindBySearchVO(searchVO, page, pageSize);
    }

    protected PageInfo<Department> internalfindBySearchVO(DepartmentSearchVO searchvo, Integer page, Integer pageSize) {
        Page<Object> pagesvo = null;
        if (page != null) {
            pagesvo = PageHelper.startPage(page, pageSize);
        }
        if (searchvo instanceof CriteriaBuilder) {
            ((CriteriaBuilder) searchvo).build();
        }
        List<Department> list = entityMapper.searchByCriteria(searchvo);
        PageInfo<Department> pageInfo = new PageInfo<Department>(list, pageSize);
        if (pagesvo != null) {
            pageInfo.setTotal(pagesvo.getTotal());
        }
        return pageInfo;
    }
}