package com.barley.party.service;

import com.barley.party.mappers.TestPartyMapper;
import com.barley.party.modal.TestParty;
import com.barley.party.modal.TestPartyKey;
import com.barley.party.service.searchvo.TestPartySearchVO;
import com.github.pagehelper.PageInfo;
import javax.transaction.NotSupportedException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.TestPartyBaseService create date 2020-12-25 13:03:26
 */
@Service
@Transactional
public class TestPartyServiceImpl implements TestPartyService {
    @Autowired
    protected TestPartyMapper entityMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public TestParty create(TestParty record) {
        entityMapper.insert(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public void delete(TestPartyKey keyId) {
        entityMapper.deleteByPrimaryKey(keyId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public TestParty update(TestParty record) {
        entityMapper.updateByPrimaryKey(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public java.util.List<TestParty> findAll() {
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public TestParty findByPrimaryKey(TestPartyKey keyId) {
        TestParty entity = entityMapper.selectByPrimaryKey(keyId);
        return entity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public PageInfo<TestParty> searchByVO(TestPartySearchVO searchVO) {
        //TODO
        throw new RuntimeException(new NotSupportedException("no support"));
    }
}