package com.barley.party.service;

import com.barley.party.mappers.TestPartyMapper;
import com.barley.party.modal.TestParty;
import com.barley.party.modal.TestPartyKey;
import com.barley.party.service.searchvo.TestPartySearchVO;
import com.github.pagehelper.Page;
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;
import java.util.List;
import org.barley.mybatis.CriteriaBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.TestPartyBaseService create date 2020-12-26 13:02:17
 */
@Service
@Transactional
public class TestPartyServiceImpl implements TestPartyService {
    @Autowired
    protected TestPartyMapper entityMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public TestParty create(TestParty record) {
        entityMapper.insert(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public void delete(TestPartyKey keyId) {
        entityMapper.deleteByPrimaryKey(keyId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public TestParty update(TestParty record) {
        entityMapper.updateByPrimaryKey(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public List<TestParty> findAll() {
        TestPartySearchVO searchvo = new TestPartySearchVO();
        return entityMapper.searchByCriteria(searchvo);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public TestParty findByPrimaryKey(TestPartyKey keyId) {
        TestParty entity = entityMapper.selectByPrimaryKey(keyId);
        return entity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public List<TestParty> searchByVO(TestPartySearchVO searchVO) {
        PageInfo<TestParty> pageInfo = internalfindBySearchVO(searchVO, null, null);
        return pageInfo.getList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public PageInfo<TestParty> searchByVO(TestPartySearchVO searchVO, int page, int pageSize) {
        return internalfindBySearchVO(searchVO, page, pageSize);
    }

    protected PageInfo<TestParty> internalfindBySearchVO(TestPartySearchVO searchvo, Integer page, Integer pageSize) {
        Page<Object> pagesvo = null;
        if (page != null) {
            pagesvo = PageHelper.startPage(page, pageSize);
        }
        if (searchvo instanceof CriteriaBuilder) {
            ((CriteriaBuilder) searchvo).build();
        }
        List<TestParty> list = entityMapper.searchByCriteria(searchvo);
        PageInfo<TestParty> pageInfo = new PageInfo<TestParty>(list, pageSize);
        if (pagesvo != null) {
            pageInfo.setTotal(pagesvo.getTotal());
        }
        return pageInfo;
    }
}