package com.barley.party.service;

import com.barley.party.mappers.UserMapper;
import com.barley.party.modal.User;
import com.barley.party.service.searchvo.UserSearchVO;
import com.github.pagehelper.PageInfo;
import javax.transaction.NotSupportedException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.UserBaseService create date 2020-12-25 13:03:26
 */
@Service
@Transactional
public class UserServiceImpl implements UserService {
    @Autowired
    protected UserMapper entityMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public User create(User record) {
        entityMapper.insert(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void delete(String keyId) {
        entityMapper.deleteByPrimaryKey(keyId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public User update(User record) {
        entityMapper.updateByPrimaryKey(record);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public java.util.List<User> findAll() {
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public User findByPrimaryKey(String keyId) {
        User entity = entityMapper.selectByPrimaryKey(keyId);
        return entity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public PageInfo<User> searchByVO(UserSearchVO searchVO) {
        //TODO
        throw new RuntimeException(new NotSupportedException("no support"));
    }
}