package com.barley.system.service.base.searchvo;

import com.barley.system.vo.BizModularCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.system.service.base.searchvo.BizModularSearchVO create date 2021-01-03 11:09:28
 */
public class BizModularSearchVO extends BizModularCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String modular;

    @Getter
    @Setter
    private Integer parentModId;

    @Getter
    @Setter
    private String describe;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(modular)) {
            criteria.andModularEqualTo(modular);
        }
        
        if(parentModId != null) {
            criteria.andParentModIdEqualTo(parentModId);
        }
        
        if(StringUtils.isNotEmpty(describe)) {
            criteria.andDescribeEqualTo(describe);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_biz_modular
     *
     * @mbg.generated
     */
    public BizModularSearchVO() {
        super();
    }
}