package com.barley.system.service.base.searchvo;

import com.barley.system.vo.LoginChannelCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.system.service.base.searchvo.LoginChannelSearchVO create date 2021-01-03 11:09:28
 */
public class LoginChannelSearchVO extends LoginChannelCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String code;

    @Getter
    @Setter
    private String descibe;

    @Getter
    @Setter
    private String secret;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(code)) {
            criteria.andCodeEqualTo(code);
        }
        
        if(StringUtils.isNotEmpty(descibe)) {
            criteria.andDescibeEqualTo(descibe);
        }
        
        if(StringUtils.isNotEmpty(secret)) {
            criteria.andSecretEqualTo(secret);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_channel
     *
     * @mbg.generated
     */
    public LoginChannelSearchVO() {
        super();
    }
}