package com.barley.system.service.base.searchvo;

import com.barley.system.vo.ModuleCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.system.service.base.searchvo.ModuleSearchVO
 */
public class ModuleSearchVO extends ModuleCriteria implements org.barley.mybatis.CriteriaBuilder {
	@Getter
	@Setter
	private Integer parentId;

	/**
	 * 是否加载子节点 (1: 加载)
	 */
	@Getter
	@Setter
	private Integer loadSub;

	@Getter
	@Setter
	private String path;

	@Getter
	@Setter
	private String name;

	@Getter
	@Setter
	private String uri;

	@Getter
	@Setter
	private Long insertBy;

	@Getter
	@Setter
	private Long updateBy;

	@Getter
	@Setter
	private java.time.LocalDateTime insertTime;

	@Getter
	@Setter
	private java.time.LocalDateTime updateTime;

	@Getter
	@Setter
	private String describe;

	@Getter
	@Setter
	private Short active;

	@Getter
	@Setter
	private Short order;

	@Getter
	@Setter
	private Integer bizModularId;

	public void build() {
		Criteria criteria = createCriteria();

		if (parentId != null) {
			criteria.andParentIdEqualTo(parentId);
		}

		if (StringUtils.isNotEmpty(path)) {
			criteria.andPathLike(path + "%");
		}

		if (StringUtils.isNotEmpty(name)) {
			criteria.andNameEqualTo(name);
		}

		if (StringUtils.isNotEmpty(uri)) {
			criteria.andUriEqualTo(uri);
		}

		if (insertBy != null) {
			criteria.andInsertByEqualTo(insertBy);
		}

		if (updateBy != null) {
			criteria.andUpdateByEqualTo(updateBy);
		}

		if (StringUtils.isNotEmpty(describe)) {
			criteria.andDescribeEqualTo(describe);
		}

		if (active != null) {
			criteria.andActiveEqualTo(active);
		}

		if (order != null) {
			criteria.andOrderEqualTo(order);
		}

		if (bizModularId != null) {
			criteria.andBizModularIdEqualTo(bizModularId);
		}
	}
	
	public boolean isLoadSub() {
		return loadSub != null && loadSub == 1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_module
	 *
	 * @mbg.generated
	 */
	public ModuleSearchVO() {
		super();
	}
}