package com.barley.system.mappers;

import com.barley.system.modal.LoginChannel;
import com.barley.system.vo.LoginChannelCriteria;
import java.util.List;

public interface LoginChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_channel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_channel
     *
     * @mbg.generated
     */
    //插入方法
    int insert(LoginChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_channel
     *
     * @mbg.generated
     */
    int insertSelective(LoginChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_channel
     *
     * @mbg.generated
     */
    List<LoginChannel> searchByCriteria(LoginChannelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_channel
     *
     * @mbg.generated
     */
    LoginChannel selectByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_channel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LoginChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_channel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoginChannel record);
}