package com.barley.system.mappers;

import com.barley.system.modal.Permission;
import com.barley.system.vo.PermissionCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Select;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated
     */
    //插入方法
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated
     */
    List<Permission> searchByCriteria(PermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated
     */
    Permission selectByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Permission record);
    
    
    /**
     * find by role
     * @param roleId
     * @return
     */
    @Select("select * from t_permission p,t_role_permission rp where p.list_id = rp.perm_id and rp.role_id = #{roleId}")
    List<Permission> findByRoleId(Integer roleId);
}