package com.barley.system.mappers;

import com.barley.system.modal.SysMessage;
import com.barley.system.vo.SysMessageCriteria;
import java.util.List;

public interface SysMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int insert(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int insertSelective(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    List<SysMessage> searchByCriteria(SysMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    SysMessage selectByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysMessage record);
}