package com.barley.system.mappers;

import com.barley.system.modal.UserStatus;
import com.barley.system.vo.UserStatusCriteria;
import java.util.List;

public interface UserStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbg.generated
     */
    int insert(UserStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbg.generated
     */
    int insertSelective(UserStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbg.generated
     */
    List<UserStatus> searchByCriteria(UserStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbg.generated
     */
    UserStatus selectByPrimaryKey(Short listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserStatus record);
}