CREATE TABLE `t_job` (
  `LIST_ID` int(11) NOT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `JOB_NAME` varchar(50) DEFAULT NULL,
  `JOB_STATUS` varchar(20) NOT NULL,
  `JOB_CLASS` varchar(200) DEFAULT NULL COMMENT '自定义执行频率',
  `JOB_FREQ` varchar(100) DEFAULT NULL COMMENT 'corn表达式',
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `ADD_BY` int(11) DEFAULT NULL,
  `UPDATE_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`LIST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

