package com.barley.config.mappers;

import com.barley.config.modal.FeildType;
import com.barley.config.vo.FeildTypeCriteria;
import java.util.List;

public interface FeildTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feild_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feild_type
     *
     * @mbg.generated
     */
    int insert(FeildType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feild_type
     *
     * @mbg.generated
     */
    int insertSelective(FeildType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feild_type
     *
     * @mbg.generated
     */
    List<FeildType> selectByExample(FeildTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feild_type
     *
     * @mbg.generated
     */
    FeildType selectByPrimaryKey(Short listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feild_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FeildType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feild_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FeildType record);
}