package com.barley.config.mappers;

import com.barley.config.modal.Form;
import com.barley.config.vo.FormCriteria;
import java.util.List;

public interface FormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated
     */
    int insert(Form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated
     */
    int insertSelective(Form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated
     */
    List<Form> selectByExample(FormCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated
     */
    Form selectByPrimaryKey(String listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Form record);
}