package com.barley.config.mappers;

import com.barley.config.modal.FormFeild;
import com.barley.config.vo.FormFeildCriteria;
import java.util.List;

public interface FormFeildMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_feild
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_feild
     *
     * @mbg.generated
     */
    //插入方法
    int insert(FormFeild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_feild
     *
     * @mbg.generated
     */
    int insertSelective(FormFeild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_feild
     *
     * @mbg.generated
     */
    List<FormFeild> searchByCriteria(FormFeildCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_feild
     *
     * @mbg.generated
     */
    FormFeild selectByPrimaryKey(Short listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_feild
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FormFeild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_feild
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FormFeild record);
}