package com.barley.config.mappers;

import com.barley.config.modal.Module;
import com.barley.config.vo.ModuleCriteria;
import java.util.List;

public interface ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated
     */
    List<Module> selectByExample(ModuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated
     */
    Module selectByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Module record);
}