package com.barley.config.modal;

import java.io.Serializable;
import org.barley.bo.AutomaticEntityImpl;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_code_table
 */
public class CodeTable extends AutomaticEntityImpl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_table.list_id
     *
     * @mbg.generated
     */
    private Long listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_table.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_table.code_name
     *
     * @mbg.generated
     */
    private String codeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_table.code_value
     *
     * @mbg.generated
     */
    private String codeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_code_table
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_table.list_id
     *
     * @return the value of t_code_table.list_id
     *
     * @mbg.generated
     */
    public Long getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_table.list_id
     *
     * @param listId the value for t_code_table.list_id
     *
     * @mbg.generated
     */
    public void setListId(Long listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_table.table_name
     *
     * @return the value of t_code_table.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_table.table_name
     *
     * @param tableName the value for t_code_table.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_table.code_name
     *
     * @return the value of t_code_table.code_name
     *
     * @mbg.generated
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_table.code_name
     *
     * @param codeName the value for t_code_table.code_name
     *
     * @mbg.generated
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_table.code_value
     *
     * @return the value of t_code_table.code_value
     *
     * @mbg.generated
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_table.code_value
     *
     * @param codeValue the value for t_code_table.code_value
     *
     * @mbg.generated
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }
}