//bubble comment line
package com.barley.config.modal;

import java.io.Serializable;
import org.barley.bo.AutomaticEntityImpl;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_feild_type
 */
//bubble java doc
public class FeildType extends AutomaticEntityImpl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feild_type.list_id
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private Short listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feild_type.type_name
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feild_type.component
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private String component;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_feild_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feild_type.list_id
     *
     * @return the value of t_feild_type.list_id
     *
     * @mbg.generated
     */
    public Short getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feild_type.list_id
     *
     * @param listId the value for t_feild_type.list_id
     *
     * @mbg.generated
     */
    public void setListId(Short listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feild_type.type_name
     *
     * @return the value of t_feild_type.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feild_type.type_name
     *
     * @param typeName the value for t_feild_type.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feild_type.component
     *
     * @return the value of t_feild_type.component
     *
     * @mbg.generated
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feild_type.component
     *
     * @param component the value for t_feild_type.component
     *
     * @mbg.generated
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }
}