//bubble comment line
package com.barley.config.modal;

import java.io.Serializable;
import org.barley.bo.AutomaticEntityImpl;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_form_feild
 */
//bubble java doc
public class FormFeild extends AutomaticEntityImpl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form_feild.list_id
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private Short listId;

    /**
     * Database Column Remarks:
     *   refer to t_form
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form_feild.form_id
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private String formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form_feild.feild_name
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private String feildName;

    /**
     * Database Column Remarks:
     *   refer to t_feild_type
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form_feild.feild_type
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private Short feildType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_form_feild
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form_feild.list_id
     *
     * @return the value of t_form_feild.list_id
     *
     * @mbg.generated
     */
    public Short getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form_feild.list_id
     *
     * @param listId the value for t_form_feild.list_id
     *
     * @mbg.generated
     */
    public void setListId(Short listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form_feild.form_id
     *
     * @return the value of t_form_feild.form_id
     *
     * @mbg.generated
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form_feild.form_id
     *
     * @param formId the value for t_form_feild.form_id
     *
     * @mbg.generated
     */
    public void setFormId(String formId) {
        this.formId = formId == null ? null : formId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form_feild.feild_name
     *
     * @return the value of t_form_feild.feild_name
     *
     * @mbg.generated
     */
    public String getFeildName() {
        return feildName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form_feild.feild_name
     *
     * @param feildName the value for t_form_feild.feild_name
     *
     * @mbg.generated
     */
    public void setFeildName(String feildName) {
        this.feildName = feildName == null ? null : feildName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form_feild.feild_type
     *
     * @return the value of t_form_feild.feild_type
     *
     * @mbg.generated
     */
    public Short getFeildType() {
        return feildType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form_feild.feild_type
     *
     * @param feildType the value for t_form_feild.feild_type
     *
     * @mbg.generated
     */
    public void setFeildType(Short feildType) {
        this.feildType = feildType;
    }
}