//bubble comment line
package com.barley.config.modal;

import java.io.Serializable;
import org.barley.bo.AutomaticEntityImpl;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_module
 */
//bubble java doc
public class Module extends AutomaticEntityImpl implements Serializable {
    /**
     * Database Column Remarks:
     *   list id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.List_id
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private Integer listId;

    /**
     * Database Column Remarks:
     *   父modal id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.parent_id
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   模块名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.mod_name
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private String modName;

    /**
     * Database Column Remarks:
     *   URI 路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.uri
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private String uri;

    /**
     * Database Column Remarks:
     *   模块描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.description
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_module
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.List_id
     *
     * @return the value of t_module.List_id
     *
     * @mbg.generated
     */
    public Integer getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.List_id
     *
     * @param listId the value for t_module.List_id
     *
     * @mbg.generated
     */
    public void setListId(Integer listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.parent_id
     *
     * @return the value of t_module.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.parent_id
     *
     * @param parentId the value for t_module.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.mod_name
     *
     * @return the value of t_module.mod_name
     *
     * @mbg.generated
     */
    public String getModName() {
        return modName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.mod_name
     *
     * @param modName the value for t_module.mod_name
     *
     * @mbg.generated
     */
    public void setModName(String modName) {
        this.modName = modName == null ? null : modName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.uri
     *
     * @return the value of t_module.uri
     *
     * @mbg.generated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.uri
     *
     * @param uri the value for t_module.uri
     *
     * @mbg.generated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.description
     *
     * @return the value of t_module.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.description
     *
     * @param description the value for t_module.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}