package com.barley.party.service;

import com.barley.party.modal.TestParty;
import com.barley.party.modal.TestPartyKey;
import com.barley.party.service.searchvo.TestPartySearchVO;
import com.github.pagehelper.PageInfo;

/**
 * Auto generate , don't modify this file.
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.TestPartyBaseService create date 2020-12-25 13:03:26
 */
public interface TestPartyBaseService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    TestParty create(TestParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    void delete(TestPartyKey keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    TestParty update(TestParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    java.util.List<TestParty> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    TestParty findByPrimaryKey(TestPartyKey keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    PageInfo<TestParty> searchByVO(TestPartySearchVO searchVO);
}