package com.barley.party.service;

import com.barley.party.modal.UserType;
import com.barley.party.service.searchvo.UserTypeSearchVO;
import com.github.pagehelper.PageInfo;
import java.util.List;

/**
 * Auto generate , don't modify this file.
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.UserTypeBaseService create date 2020-12-27 14:50:38
 */
public interface UserTypeBaseService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbg.generated
     */
    UserType create(UserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbg.generated
     */
    void delete(Short keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbg.generated
     */
    UserType update(UserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbg.generated
     */
    List<UserType> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbg.generated
     */
    UserType findByPrimaryKey(Short keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbg.generated
     */
    List<UserType> searchByVO(UserTypeSearchVO searchVO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbg.generated
     */
    PageInfo<UserType> searchByVO(UserTypeSearchVO searchVO, int page, int pageSize);
}