package com.barley.party.service.searchvo;

import com.barley.party.vo.EmployeeCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.searchvo.EmployeeSearchVO create date 2020-12-26 13:02:17
 */
public class EmployeeSearchVO extends EmployeeCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String ename;

    @Getter
    @Setter
    private Long insertBy;

    @Getter
    @Setter
    private Long updateBy;

    @Getter
    @Setter
    private java.time.LocalDateTime insertTime;

    @Getter
    @Setter
    private java.time.LocalDateTime updateTime;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(ename)) {
            criteria.andEnameEqualTo(ename);
        }
        
        if(insertBy != null) {
            criteria.andInsertByEqualTo(insertBy);
        }
        
        if(updateBy != null) {
            criteria.andUpdateByEqualTo(updateBy);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbg.generated
     */
    public EmployeeSearchVO() {
        super();
    }
}