package com.barley.party.service.searchvo;

import lombok.Getter;
import lombok.Setter;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.searchvo.EmployeeSearchVO create date 2020-12-25 13:03:26
 */
public class EmployeeSearchVO {
    @Getter
    @Setter
    private String ename;

    @Getter
    @Setter
    private Long insertBy;

    @Getter
    @Setter
    private Long updateBy;

    @Getter
    @Setter
    private java.time.LocalDateTime insertTime;

    @Getter
    @Setter
    private java.time.LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbg.generated
     */
    public EmployeeSearchVO() {
        super();
    }
}