package com.barley.party.service.searchvo;

import com.barley.party.vo.OrganizationCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.searchvo.OrganizationSearchVO create date 2020-12-26 12:52:22
 */
public class OrganizationSearchVO extends OrganizationCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String comment;

    @Getter
    @Setter
    private String orgCode;

    @Getter
    @Setter
    private String orgName;

    @Getter
    @Setter
    private Integer orgStatus;

    @Getter
    @Setter
    private String parentId;

    @Getter
    @Setter
    private Integer sortOrder;

    @Getter
    @Setter
    private Long insertBy;

    @Getter
    @Setter
    private Long updateBy;

    @Getter
    @Setter
    private java.time.LocalDateTime insertTime;

    @Getter
    @Setter
    private java.time.LocalDateTime updateTime;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(comment)) {
            criteria.andCommentEqualTo(comment);
        }
        
        if(StringUtils.isNotEmpty(orgCode)) {
            criteria.andOrgCodeEqualTo(orgCode);
        }
        
        if(StringUtils.isNotEmpty(orgName)) {
            criteria.andOrgNameEqualTo(orgName);
        }
        
        if(orgStatus != null) {
            criteria.andOrgStatusEqualTo(orgStatus);
        }
        
        if(StringUtils.isNotEmpty(parentId)) {
            criteria.andParentIdEqualTo(parentId);
        }
        
        if(sortOrder != null) {
            criteria.andSortOrderEqualTo(sortOrder);
        }
        
        if(insertBy != null) {
            criteria.andInsertByEqualTo(insertBy);
        }
        
        if(updateBy != null) {
            criteria.andUpdateByEqualTo(updateBy);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbg.generated
     */
    public OrganizationSearchVO() {
        super();
    }
}