package com.barley.party.service.searchvo;

import com.barley.party.vo.TestPartyCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.searchvo.TestPartySearchVO create date 2020-12-27 14:50:38
 */
public class TestPartySearchVO extends TestPartyCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String name;

    @Getter
    @Setter
    private String desc;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(name)) {
            criteria.andNameEqualTo(name);
        }
        
        if(StringUtils.isNotEmpty(desc)) {
            criteria.andDescEqualTo(desc);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public TestPartySearchVO() {
        super();
    }
}