package com.barley.party.service.searchvo;

import lombok.Getter;
import lombok.Setter;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.searchvo.TestPartySearchVO create date 2020-12-25 13:03:26
 */
public class TestPartySearchVO {
    @Getter
    @Setter
    private String name;

    @Getter
    @Setter
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_party
     *
     * @mbg.generated
     */
    public TestPartySearchVO() {
        super();
    }
}