package com.barley.party.service.searchvo;

import lombok.Getter;
import lombok.Setter;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.searchvo.UserTypeSearchVO create date 2020-12-25 13:03:26
 */
public class UserTypeSearchVO {
    @Getter
    @Setter
    private String typeName;

    @Getter
    @Setter
    private String typeCode;

    @Getter
    @Setter
    private Short typeStatus;

    @Getter
    @Setter
    private Long insertBy;

    @Getter
    @Setter
    private Long updateBy;

    @Getter
    @Setter
    private java.time.LocalDateTime insertTime;

    @Getter
    @Setter
    private java.time.LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbg.generated
     */
    public UserTypeSearchVO() {
        super();
    }
}