package com.barley.party.service.searchvo;

import lombok.Getter;
import lombok.Setter;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.party.service.searchvo.UserSearchVO create date 2020-12-25 13:03:26
 */
public class UserSearchVO {
    @Getter
    @Setter
    private java.time.LocalDateTime activationTime;

    @Getter
    @Setter
    private java.time.LocalDate applicationTime;

    @Getter
    @Setter
    private String email;

    @Getter
    @Setter
    private java.time.LocalDateTime firstLoginTime;

    @Getter
    @Setter
    private java.time.LocalDateTime lastLoginTime;

    @Getter
    @Setter
    private String loginName;

    @Getter
    @Setter
    private Integer loginTimes;

    @Getter
    @Setter
    private String password;

    @Getter
    @Setter
    private String sourceId;

    @Getter
    @Setter
    private String spell;

    @Getter
    @Setter
    private Integer userStatus;

    @Getter
    @Setter
    private Integer userType;

    @Getter
    @Setter
    private Long insertBy;

    @Getter
    @Setter
    private Long updateBy;

    @Getter
    @Setter
    private java.time.LocalDateTime insertTime;

    @Getter
    @Setter
    private java.time.LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public UserSearchVO() {
        super();
    }
}