package com.barley.system.service.auth.searchvo;

import com.barley.system.vo.PermissionCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.system.service.auth.searchvo.PermissionSearchVO create date 2021-01-03 11:09:28
 */
public class PermissionSearchVO extends PermissionCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String code;

    @Getter
    @Setter
    private String describe;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(code)) {
            criteria.andCodeEqualTo(code);
        }
        
        if(StringUtils.isNotEmpty(describe)) {
            criteria.andDescribeEqualTo(describe);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated
     */
    public PermissionSearchVO() {
        super();
    }
}