package com.barley.system.service.auth.searchvo;

import com.barley.system.vo.RoleCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.system.service.auth.searchvo.RoleSearchVO create date 2021-01-03 11:09:28
 */
public class RoleSearchVO extends RoleCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String name;

    @Getter
    @Setter
    private String describe;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(name)) {
            criteria.andNameEqualTo(name);
        }
        
        if(StringUtils.isNotEmpty(describe)) {
            criteria.andDescribeEqualTo(describe);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated
     */
    public RoleSearchVO() {
        super();
    }
}