package com.barley.system.service.auth.searchvo;

import com.barley.system.vo.RoleCriteria;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

/**
 * @author peculiar.1@163.com
 * @version $ID: com.barley.system.service.auth.searchvo.RoleSearchVO
 */
public class RoleSearchVO extends RoleCriteria implements org.barley.mybatis.CriteriaBuilder {
    @Getter
    @Setter
    private String name;

    @Getter
    @Setter
    private String describe;

    @Getter
    @Setter
    private Long insertBy;

    @Getter
    @Setter
    private Long updateBy;

    @Getter
    @Setter
    private java.time.LocalDateTime insertTime;

    @Getter
    @Setter
    private java.time.LocalDateTime updateTime;

    public void build() {
        Criteria criteria = createCriteria();
        
        if(StringUtils.isNotEmpty(name)) {
            criteria.andNameEqualTo(name);
        }
        
        if(StringUtils.isNotEmpty(describe)) {
            criteria.andDescribeEqualTo(describe);
        }
        
        if(insertBy != null) {
            criteria.andInsertByEqualTo(insertBy);
        }
        
        if(updateBy != null) {
            criteria.andUpdateByEqualTo(updateBy);
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated
     */
    public RoleSearchVO() {
        super();
    }
}