//bubble comment line
package com.barley.party.modal;

import java.io.Serializable;
import org.barley.bo.AutomaticEntityImpl;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_type
 */
//bubble java doc
public class UserType extends AutomaticEntityImpl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_type.list_id
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private Short listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_type.type_name
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_type.type_code
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private String typeCode;

    /**
     * Database Column Remarks:
     *   0 inactive, 1 active
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_type.type_status
     *
     * @mbg.generated
     */
    /**bubble field comments*/
    private Short typeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_type.list_id
     *
     * @return the value of t_user_type.list_id
     *
     * @mbg.generated
     */
    public Short getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_type.list_id
     *
     * @param listId the value for t_user_type.list_id
     *
     * @mbg.generated
     */
    public void setListId(Short listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_type.type_name
     *
     * @return the value of t_user_type.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_type.type_name
     *
     * @param typeName the value for t_user_type.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_type.type_code
     *
     * @return the value of t_user_type.type_code
     *
     * @mbg.generated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_type.type_code
     *
     * @param typeCode the value for t_user_type.type_code
     *
     * @mbg.generated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_type.type_status
     *
     * @return the value of t_user_type.type_status
     *
     * @mbg.generated
     */
    public Short getTypeStatus() {
        return typeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_type.type_status
     *
     * @param typeStatus the value for t_user_type.type_status
     *
     * @mbg.generated
     */
    public void setTypeStatus(Short typeStatus) {
        this.typeStatus = typeStatus;
    }
}